import type { Metadata } from "next";
import '../styles/global.scss';
import MenuComponent from '@/app/components/menu'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="main-container">
      <MenuComponent/>
        {children}
        </body>
    </html>
  );
}
